services:
  - type: web
    name: ritgate-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: BACKEND_BASE_URL
        value: https://ritgate-backend.onrender.com
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
