services:
  - type: web
    name: ritgate-backend
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BACKEND_BASE_URL
        value: https://ritgate-backend.onrender.com
      - key: PORT
        value: "8080"
